# Generated by Django 5.0.3 on 2024-03-21 08:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), size=3),
        ),
    ]
