# Generated by Django 5.0.3 on 2024-03-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_employee__name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='_middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
