# Generated by Django 5.0.3 on 2024-03-21 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_remove_employee__name_employee__first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='_middle_name',
            new_name='middle_name',
        ),
    ]
