# Generated by Django 5.0.3 on 2024-03-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_rename__first_name_employee_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='tax_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
