# Generated by Django 5.0.3 on 2024-03-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_employee_tax_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='tax_number',
            field=models.CharField(max_length=100),
        ),
    ]
