# Generated by Django 5.0.3 on 2024-05-26 08:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_settingcategory_taxcode_settingcategoryfield_setting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accumulator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='AllowanceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.RemoveField(
            model_name='settingcategoryfield',
            name='category',
        ),
        migrations.AddField(
            model_name='transaction',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tax_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.taxcode', verbose_name='Tax Code'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tax_number',
            field=models.CharField(max_length=100, verbose_name='Tax Number'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='allowance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.allowance'),
        ),
        migrations.AddField(
            model_name='allowance',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.allowancetype'),
        ),
        migrations.CreateModel(
            name='AllowanceTypeAccumulator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accumulator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.accumulator')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.allowancetype')),
            ],
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
        migrations.DeleteModel(
            name='SettingCategory',
        ),
        migrations.DeleteModel(
            name='SettingCategoryField',
        ),
    ]
