# Generated by Django 5.0.3 on 2024-05-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_accumulator_allowance_allowancetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accumulator',
            name='unit',
            field=models.CharField(choices=[('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('amount', 'Amount')], default='amount', max_length=20),
        ),
    ]
