# Generated by Django 5.0.3 on 2024-05-26 09:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_accumulator_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='PayPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('fourweekly', 'Fourweekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.paygroup')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='for_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_period', to='payroll.payperiod'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pay_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_period', to='payroll.payperiod'),
        ),
    ]
