# Generated by Django 5.0.3 on 2024-05-27 02:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_paygroup_payperiod_transaction_for_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='payroll.allowancetype'),
        ),
        migrations.AlterField(
            model_name='allowancetypeaccumulator',
            name='accumulator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowance_types', to='payroll.accumulator'),
        ),
        migrations.AlterField(
            model_name='allowancetypeaccumulator',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_accumulators', to='payroll.allowancetype'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='allowance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payroll.allowance'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payroll.employee'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='for_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_period_transactions', to='payroll.payperiod'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pay_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pay_period_transactions', to='payroll.payperiod'),
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('factor', models.FloatField(default=1)),
                ('days_range', models.IntegerField(default=1)),
                ('reference_date', models.CharField(choices=[('period_date', 'Period Date'), ('transaction_date', 'Transaction Date')], default='transaction_date', max_length=100)),
                ('denominator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_denominator_rates', to='payroll.accumulator')),
                ('numerator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_numerator_rates', to='payroll.accumulator')),
            ],
        ),
    ]
