# Generated by Django 5.0.3 on 2024-06-01 08:39

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_alter_allowance_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCustomField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Field Name')),
                ('description', models.CharField(max_length=200, verbose_name='Field Description')),
                ('type', models.CharField(choices=[('str', 'String'), ('int', 'Integer'), ('float', 'Float'), ('date', 'Date')], default='str', verbose_name='Field Type')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeCustomFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_value', models.CharField(max_length=200, verbose_name='Value')),
                ('effective_date', models.DateField(default=datetime.datetime.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employeecustomfield')),
            ],
        ),
    ]
