# Generated by Django 5.0.3 on 2024-06-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_employeecustomfield_employeecustomfieldvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='unit',
            field=models.CharField(choices=[('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('quantity', 'Quantity'), ('amount', 'Amount')], default='hours', max_length=20),
        ),
        migrations.AlterField(
            model_name='accumulator',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='accumulator',
            name='unit',
            field=models.CharField(choices=[('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('quantity', 'Quantity'), ('amount', 'Amount')], default='amount', max_length=20),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='allowancetype',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='paygroup',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='allowancetypeaccumulator',
            unique_together={('type', 'accumulator')},
        ),
    ]
