# Generated by Django 5.0.3 on 2024-06-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_rate_unit_alter_accumulator_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='end',
            field=models.IntegerField(default=1439),
        ),
        migrations.AddField(
            model_name='transaction',
            name='start',
            field=models.IntegerField(default=0),
        ),
    ]
