# Generated by Django 5.0.3 on 2024-06-12 03:53

import payroll.models.employee
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0016_populate_employee_code_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="code",
            field=models.CharField(
                default=payroll.models.employee.generate_code,
                max_length=5,
                unique=True,
                verbose_name="Employee Code",
            ),
        ),
    ]
