# Generated by Django 5.0.3 on 2024-06-12 04:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0017_remove_employee_code_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=400)),
                ('cycle_length', models.IntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='RosterEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_start', models.DateField(default='1900-01-01')),
                ('effective_end', models.DateField(default='9999-12-31')),
                ('offset', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_employees', to='payroll.employee')),
                ('roster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='payroll.roster')),
            ],
        ),
        migrations.CreateModel(
            name='RosterShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=400)),
                ('order', models.IntegerField(default=0)),
                ('start', models.IntegerField(default=510.0)),
                ('end', models.IntegerField(default=1020)),
                ('unpaid_break', models.IntegerField(default=30)),
                ('roster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='payroll.roster')),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('unpaid_break', models.IntegerField(default=30)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='payroll.employee')),
            ],
        ),
    ]
