# Generated by Django 5.0.3 on 2024-06-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0018_roster_rosteremployee_rostershift_timesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='denominator_cap',
            field=models.FloatField(default=9999999),
        ),
    ]
