# Generated by Django 5.0.3 on 2024-06-12 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0019_rate_denominator_cap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=400)),
                ('start', models.IntegerField(default=510.0)),
                ('end', models.IntegerField(default=1020)),
                ('unpaid_break', models.IntegerField(default=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='rostershift',
            name='code',
        ),
        migrations.RemoveField(
            model_name='rostershift',
            name='description',
        ),
        migrations.RemoveField(
            model_name='rostershift',
            name='end',
        ),
        migrations.RemoveField(
            model_name='rostershift',
            name='start',
        ),
        migrations.RemoveField(
            model_name='rostershift',
            name='unpaid_break',
        ),
        migrations.AddField(
            model_name='rostershift',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.shift'),
        ),
    ]
