# Generated by Django 5.0.3 on 2024-06-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0020_shift_remove_rostershift_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paygroup',
            name='code',
            field=models.CharField(db_column='code', max_length=100, unique=True),
        ),
        migrations.RenameField(
            model_name='paygroup',
            old_name='code',
            new_name='_code',
        ),
        migrations.AlterUniqueTogether(
            name='payperiod',
            unique_together={('group', 'end')},
        ),
    ]
