# Generated by Django 5.0.3 on 2024-06-16 05:12

from django.db import migrations
from django.utils.text import slugify


def slugify_codes(apps, schema_editor):
    PayGroup = apps.get_model("payroll", "PayGroup")
    for pay_group in PayGroup.objects.all():
        pay_group._code = slugify(pay_group._code)
        pay_group.save(update_fields=["_code"])


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0021_alter_paygroup_code_rename_code_paygroup__code_and_more"),
    ]

    operations = [
        migrations.RunPython(slugify_codes),
    ]
