# Generated by Django 5.0.3 on 2024-06-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0022_update_paygroup_code_slugify"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paygroup",
            name="_code",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RenameField(
            model_name="paygroup", old_name="_code", new_name="code"
        ),
    ]
