# Generated by Django 5.0.3 on 2024-06-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0023_rename_paygroup_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecustomfieldvalue',
            name='_value',
        ),
        migrations.AddField(
            model_name='employeecustomfieldvalue',
            name='value',
            field=models.CharField(max_length=200, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='employeecustomfield',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Field Name'),
        ),
        migrations.AlterField(
            model_name='employeecustomfieldvalue',
            name='effective_date',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
