# Generated by Django 5.0.3 on 2024-06-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0024_remove_employeecustomfieldvalue__value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecustomfield',
            name='code',
            field=models.CharField(default='code', max_length=50, unique=True, verbose_name='Field Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeecustomfield',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Field Name'),
        ),
    ]
